### ISSUE TITLE
network.lua新增代码导致打开“网络”-“接口”时luci报错

### ISSUE THREAD

**Issue by FunnyFly-ZW** [coolsnowwolf/luci#107]
报错如图，手动删除114-115行后恢复正常。
[关联Commit](https://github.com/coolsnowwolf/luci/commit/d607d49bf13024ff027ce608e03980f0176ac76f)
![image](https://user-images.githubusercontent.com/41453032/160225926-e82f36eb-d140-48c3-81b0-4db6aa53928d.png)

**Comment by firkerword** [comment]
我还纳闷是怎么回事呢😰

**Comment by Beginner-Go** [comment]
不是修好了？
