### ISSUE TITLE
阿里云盘 WebDAV勾选启用无用

### ISSUE THREAD

**Issue by liwenjie119** [coolsnowwolf/luci#117]
勾选启用和停用没法立即启用和停用，只能通过重启路由器实现启用和停用，Refresh Token失效了替换的时候需要重启才成

**Comment by Beginner-Go** [comment]
(https://github.com/messense/aliyundrive-webdav)[向上游反馈]

**Comment by Beginner-Go** [comment]
可能是您自身的问题,似乎其他人没有遇到这bug

**Comment by WYC-2020** [comment]
经过我权威验证没任何问题哈哈

**Comment by EnnawYang** [comment]
天天在用，没问题
