### ISSUE TITLE
主题显示不一样

### ISSUE THREAD

**Issue by nature2608** [coolsnowwolf/luci#12]
同一个ipk，我安装在您的源码编译的固件上会显示的很简单，有些地方也不正常。
![微信图片_20191010020234](https://user-images.githubusercontent.com/32662472/66508509-de637500-eb03-11e9-9080-c58bb85464ec.png)
![微信截图_20191010020335](https://user-images.githubusercontent.com/32662472/66508510-de637500-eb03-11e9-99b1-ba015908c20b.png)
![微信截图_20191010020528](https://user-images.githubusercontent.com/32662472/66508511-de637500-eb03-11e9-8010-abaf413c9289.png)
而安装在openwrt官方的固件上则是正常的。
![微信截图_20191010021220](https://user-images.githubusercontent.com/32662472/66508559-f5a26280-eb03-11e9-91b3-f73cb747ad60.png)
![微信截图_20191010021236](https://user-images.githubusercontent.com/32662472/66508560-f5a26280-eb03-11e9-88ee-0abb118b1546.png)
![微信截图_20191010021247](https://user-images.githubusercontent.com/32662472/66508561-f63af900-eb03-11e9-9e79-af988dfa6111.png)

用的是官方带的rosy主题。我如果切换主题的话也是不正常。

**Comment by outemancut** [comment]
让这个主题的开发者来做兼容就是了 默认的主题虽然没有你们的花里胡哨 但是是兼容跟性能最强的 这种问题要么自己做解决要么用默认主题！

**Comment by nature2608** [comment]
@outemancut 兼容性的确是，用官方的luci很奇怪
