### ISSUE TITLE
luci-app-aliyundrive-fuse v01.12版本已支持mipsel架构，下载报错需要更改lede/feeds/packages/multimedia/aliyundrive-fuse路径的makefile

### ISSUE THREAD

**Issue by ENEN-YIN** [coolsnowwolf/luci#126]
将路径lede/feeds/packages/multimedia/aliyundrive-fuse的makefile文件中
PKG_VERSION:=0.1.9
改为
PKG_VERSION:=0.1.12
即可

ps：小白第一次issue，如有不对请指出

**Comment by WYC-2020** [comment]
如果有hash hash也要修改，可不是简单改这个，并且看下还有patch没 如果有patch 看下patch 有必要更新不
