### ISSUE TITLE
wireguard编译报错，是不是上游更新了啥东西啊大佬

### ISSUE THREAD

**Issue by MXJNZ6** [coolsnowwolf/luci#128]
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kernel/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.kernel_installed
Package kmod-wireguard is missing dependencies for the following libraries:
libblake2s.ko
make[3]: *** [/workdir/openwrt/bin/targets/x86/64/packages/kmod-wireguard_5.4.195-1_x86_64.ipk] Error 1
modules/netsupport.mk:1313: recipe for target '/workdir/openwrt/bin/targets/x86/64/packages/kmod-wireguard_5.4.195-1_x86_64.ipk' failed
make[3]: Leaving directory '/workdir/openwrt/package/kernel/linux'
time: package/kernel/linux/compile#2.80#0.25#3.03
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/kernel/linux/compile] Error 1
package/Makefile:114: recipe for target 'package/kernel/linux/compile' failed
make[2]: Leaving directory '/workdir/openwrt'
package/Makefile:110: recipe for target '/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [world] Error 2
/workdir/openwrt/include/toplevel.mk:228: recipe for target 'world' failed
Error: Process completed with exit code 2.

**Comment by WYC-2020** [comment]
这个应该修复了，不过看修复方式猜测5.10应该编译不过，除非吧5.10升级到119以上
