### ISSUE TITLE
applications/luci-app-socat 发现适配问题，直接这个仓库还是哪里修改

### ISSUE THREAD

**Issue by zhangguanzhang** [coolsnowwolf/luci#138]
发现一个适配问题，我看Makefile包作者是 https://github.com/Lienol 但是他的 github 没找到 luci-app-socat，那我应该在本仓库直接提 pr 吗
```
./luasrc/controller/socat.lua
./root/etc/init.d/luci_socat
```

**Comment by Beginner-Go** [comment]
https://github.com/Lienol/openwrt-package/tree/main/luci-app-socat

**Comment by zhangguanzhang** [comment]
1
