### ISSUE TITLE
luci-theme-argon-mod 与 luci-theme-argon 主题冲突

### ISSUE THREAD

**Issue by smallprogram** [coolsnowwolf/luci#151]
```shell
ConfiguriCollected errors:
 * check_data_file_clashes: Package luci-theme-argon-mod wants to install file /home/zhusir/lede_x64.config/build_dir/target-x86_64_musl/root-x86/usr/lib/lua/luci/view/themes/argon/footer.htm
        But that file is already provided by package  * luci-theme-argon
 * check_data_file_clashes: Package luci-theme-argon-mod wants to install file /home/zhusir/lede_x64.config/build_dir/target-x86_64_musl/root-x86/usr/lib/lua/luci/view/themes/argon/header.htm
        But that file is already provided by package  * luci-theme-argon
 * check_data_file_clashes: Package luci-theme-argon-mod wants to install file /home/zhusir/lede_x64.config/build_dir/target-x86_64_musl/root-x86/www/luci-static/argon/favicon.ico
        But that file is already provided by package  * luci-theme-argon
 * check_data_file_clashes: Package luci-theme-argon-mod wants to install file /home/zhusir/lede_x64.config/build_dir/target-x86_64_musl/root-x86/www/luci-static/argon/js/jquery.min.js
        But that file is already provided by package  * luci-theme-argon
 * check_data_file_clashes: Package luci-theme-argon-mod wants to install file /home/zhusir/lede_x64.config/build_dir/target-x86_64_musl/root-x86/www/luci-static/argon/js/script.js
        But that file is already provided by package  * luci-theme-argon
 * opkg_install_cmd: Cannot install package luci-theme-argon-mod.
```

**Comment by aiamadeus** [comment]
这是肯定会冲突的，你只能选其中一个。

**Comment by GreatMichaelLee** [comment]
> 这是肯定会冲突的，你只能选其中一个。

@aiamadeus 你自己试过mod编译没有，根本就编译不过！menu configure里，luci-app-argon是强制选择的，即便我手工编辑.config里吧luci-app-argon=y改成N,编译还是会报错！

![image](https://user-images.githubusercontent.com/20067401/185795095-83084be1-7c5a-46b4-a757-1ed0c66166d2.png)

**Comment by EnnawYang** [comment]
> > 这是肯定会冲突的，你只能选其中一个。
> 
> @aiamadeus 你自己试过mod编译没有，根本就编译不过！menu configure里，luci-app-argon是强制选择的，即便我手工编辑.config里吧luci-app-argon=y改成N, 然后rm -rf ./tmp && make clean,进行干净编译还是会报错！
> 

那可能我用的是假的？

<img width="996" alt="Snipaste_2022-08-21_22-20-00" src="https://user-images.githubusercontent.com/6705663/185795533-2c1dccea-3ed6-4ac5-8dfe-acc05cf64045.png">

**Comment by GreatMichaelLee** [comment]
> > > 这是肯定会冲突的，你只能选其中一个。
> > 
> > 
> > @aiamadeus 你自己试过mod编译没有，根本就编译不过！menu configure里，luci-app-argon是强制选择的，即便我手工编辑.config里吧luci-app-argon=y改成N, 然后rm -rf ./tmp && make clean,进行干净编译还是会报错！
> 
> 那可能我用的是假的？
> 
> <img alt="Snipaste_2022-08-21_22-20-00" width="996" src="https://user-images.githubusercontent.com/6705663/185795533-2c1dccea-3ed6-4ac5-8dfe-acc05cf64045.png">

you are developer, so you tell me.

**Comment by aiamadeus** [comment]
> 你自己试过mod编译没有，根本就编译不过！

你自己没改 luci-app-argon-config 的依赖罢了。
另外说话麻烦客气一点，我不欠谁什么。

**Comment by GreatMichaelLee** [comment]
![image](https://user-images.githubusercontent.com/20067401/185796034-4c86ed44-4694-4e89-b05b-bb1dbbd92853.png

**Comment by GreatMichaelLee** [comment]
![image](https://user-images.githubusercontent.com/20067401/185796079-649f8cba-0957-4154-a8c0-a330496302e0.png)

**Comment by GreatMichaelLee** [comment]
> > 你自己试过mod编译没有，根本就编译不过！
> 
> 你自己没改 luci-app-argon-config 的依赖罢了。 另外说话麻烦客气一点，我不欠谁什么。

跟luci-app-argon-config有什么关系？我看menu configure里这个luci-theme-argon是被luci依赖了。我不知道为什么

**Comment by GreatMichaelLee** [comment]
我搞定了，感谢两位，无意冒犯，经济不好，比较焦虑而已-_-!

**Comment by smallprogram** [comment]
@GreatMichaelLee 哈哈哈哈😂
