### ISSUE TITLE
为何luci-theme-argon变成这个样子了？

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/luci#152]
之前的argon主题不是这样的

![image](https://user-images.githubusercontent.com/20067401/185568642-a126e086-984e-4b3d-831a-97b58225c892.png)

**Comment by aiamadeus** [comment]
u1s1，argon 本来就长这样，你要的那个主题叫 argon-mod。

**Comment by GreatMichaelLee** [comment]
> u1s1，argon 本来就长这样，你要的那个主题叫 argon-mod。

argon-mod勾上后根本编译不过，提示依赖argon主题，但你又说只能二选一，非常confuse.

**Comment by cxgreat2014** [comment]
> > u1s1，argon 本来就长这样，你要的那个主题叫 argon-mod。
> 
> argon-mod勾上后根本编译不过，提示依赖argon主题，但你又说只能二选一，非常confuse.

有没有一种可能，他没说只能二选一
