### ISSUE TITLE
luci-app-aria2 安装后的菜单位置问题？

### ISSUE THREAD

**Issue by garryshield** [coolsnowwolf/luci#154]
有看到

https://github.com/coolsnowwolf/luci/blob/874429fe7237b5ef97381098ea6646a55df78b88/applications/luci-app-aria2/luasrc/controller/aria2.lua#L21

luci-app-aria2 是指定安装到 `/admin/services/aria2` 下的
为什么安装后 会跑到 `/admin/nas/aria2`

是不是什么地方做了修改？

**Comment by EnnawYang** [comment]
https://github.com/coolsnowwolf/lede/blob/master/package/lean/default-settings/files/zzz-default-settings#L18

**Comment by garryshield** [comment]
@EnnawYang nice
