### ISSUE TITLE
simpleform 部分功能缺失

### ISSUE THREAD

**Issue by lisaac** [coolsnowwolf/luci#16]
在 simpleform 实际使用过程中，部分方法失效，均与 js 有关
- Value 中的 :value() 方法失效
- DynamicList 失效
- :depends() 方法失效

初步判定是 simpleform 中缺失js 方法 cbi_init() 所致，但是仍存在一些问题，烦请大佬解决。

**Comment by coolsnowwolf** [comment]
我看看

**Comment by lisaac** [comment]
@coolsnowwolf 
#17 这个 PR 解决了这个问题
