### ISSUE TITLE
TurboACC高性能模式，貌似无法启动？

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [coolsnowwolf/luci#165]
拉取了最新源码编译，选了高性能模式，还是显示未运行，选兼容模式，确实是运行的。

选禁用和高性能模式：
Chain zone_wan_postrouting (0 references)
target prot opt source destination
postrouting_wan_rule all -- anywhere anywhere /* !fw3: Custom wan postrouting rule chain /
MASQUERADE all -- anywhere anywhere / !fw3 */

![image](https://user-images.githubusercontent.com/32566723/203259324-837dd127-c82c-4af7-b7a8-78e026bfc233.png)

选兼容模式：
Chain zone_wan_postrouting (0 references)
target prot opt source destination
postrouting_wan_rule all -- anywhere anywhere /* !fw3: Custom wan postrouting rule chain /
FULLCONENAT all -- anywhere anywhere / !fw3 */

![image](https://user-images.githubusercontent.com/32566723/203259250-cec7ae0d-1c9f-4deb-8241-b3bd693a6db9.png)

**Comment by zxlhhyccc** [comment]
我也是一样无法启动。。。。

**Comment by aiamadeus** [comment]
很简单，就只有 luci 支持了而已，高性能模式不存在。

**Comment by zxlhhyccc** [comment]
> 很简单，就只有 luci 支持了而已，高性能模式不存在。

有道理，但为啥要添加高性能？

**Comment by WCJ23333** [comment]
在防火墙中更改为高性能模式，turbo acc中状态无法同步，仍然显示兼容模式
查看/etc/config/turboacc  发现  option fullcone_nat '1'  也就是值没有更改为2

更改为高性能模式时，全锥形NAT会显示未运行
