### ISSUE TITLE
Turbo ACC 未适配 FullCone-NAT 高性能模式

### ISSUE THREAD

**Issue by WCJ23333** [coolsnowwolf/luci#168]
在防火墙中更改为高性能模式，turbo acc中状态无法同步，仍然显示兼容模式
查看/etc/config/turboacc  发现  option fullcone_nat '1'  也就是值没有更改为2

更改为高性能模式时，全锥形NAT会显示未运行

_Originally posted by @WCJ23333 in https://github.com/coolsnowwolf/luci/issues/165#issuecomment-1326193918_

**Comment by zxlhhyccc** [comment]
> 在防火墙中更改为高性能模式，turbo acc中状态无法同步，仍然显示兼容模式 查看/etc/config/turboacc 发现 option fullcone_nat '1' 也就是值没有更改为2
> 
> 更改为高性能模式时，全锥形NAT会显示未运行
> 
> _Originally posted by @WCJ23333 in [#165 (comment)](https://github.com/coolsnowwolf/luci/issues/165#issuecomment-1326193918)_

大屌目前还没开源，所以你现在用不了的。。。
