### ISSUE TITLE
L大，luci-app-adbyby-plus报错了

### ISSUE THREAD

**Issue by rongcenter** [coolsnowwolf/luci#175]
change conf dir to fix adbyby working with dnsmasq and proc-ujail (#173)

init.d/adbyby
WAN_FILE=/var/etc/dnsmasq-adbyby.d/03-adbyby-ipset.conf

WAN_FILE=/tmp/dnsmasq.d/dnsmasq-adbyby.d/03-adbyby-ipset.conf

好像漏改了。

**Comment by rongcenter** [comment]
除了这个，目前使用正常了

**Comment by Gabrielxzx** [comment]
> 除了这个，目前使用正常了

问下除了这个还需要修改别的地方吗？按照你的修改后，现在执行更新规则命令还是会报错，
执行的更新命令规则是：
`/usr/share/adbyby/adblock.sh`
报错如下：
`rm: '/tmp/dnsmasq.d/dnsmasq-adbyby.d/rules' is a directory
`
附图如下：
![image](https://user-images.githubusercontent.com/27126997/216316807-95f52ca7-8933-4bd6-ba3c-7af4f74f2b1d.png)
