### ISSUE TITLE
解决 luci-app-baidupcs-web 在官方 OpenWrt 22.03.2 中无法运行的问题

### ISSUE THREAD

**Issue by zhengmz** [coolsnowwolf/luci#179]
需要修改两个地方：

1. 修改 `/etc/init.d/baidupcs-web`: 将此行注释，在行首加 `#`
https://github.com/coolsnowwolf/luci/blob/a7f754dfbe07faa12bb04746a6ec751a94d13d61/applications/luci-app-baidupcs-web/root/etc/init.d/baidupcs-web#L15
修改成: `#	stop`

2. 修改 `view/baidupcs-web/baidupcs-web_status.htm`: 在 id 中增加 `widget.`
https://github.com/coolsnowwolf/luci/blob/a7f754dfbe07faa12bb04746a6ec751a94d13d61/applications/luci-app-baidupcs-web/luasrc/view/baidupcs-web/baidupcs-web_status.htm#L27
修改成： `	var clientPort = window.document.getElementById("widget.cbid.baidupcs-web.config.port").value`

**Comment by hue715** [comment]
这是因为/etc/init.d/baidupcs-web与执行文件重名了，个人觉得可以把luci界面更名

> 需要修改两个地方：
> 
> 1. 修改 `/etc/init.d/baidupcs-web`: 将此行注释，在行首加 `#`
>    https://github.com/coolsnowwolf/luci/blob/a7f754dfbe07faa12bb04746a6ec751a94d13d61/applications/luci-app-baidupcs-web/root/etc/init.d/baidupcs-web#L15
>    
>    修改成: `#	stop`

**Comment by zhengmz** [comment]
> 这是因为/etc/init.d/baidupcs-web与执行文件重名了，个人觉得可以效仿此更改#101
> 
> > 需要修改两个地方：
> > 
> > 1. 修改 `/etc/init.d/baidupcs-web`: 将此行注释，在行首加 `#`
> >    https://github.com/coolsnowwolf/luci/blob/a7f754dfbe07faa12bb04746a6ec751a94d13d61/applications/luci-app-baidupcs-web/root/etc/init.d/baidupcs-web#L15
> >    
> >    修改成: `#	stop`

有理
