### ISSUE TITLE
The value of 'URL routing' cannot be correctly saved to the configuration file in 'luci-app-frpc'

### ISSUE THREAD

**Issue by IDeLoveYou** [coolsnowwolf/luci#183]
I may have some problems with my English, please forgive me for using translator to explain this, when I was using frpc, I changed and saved the value of "URL routing", but when I refreshed the page, the value disappeared, and I did not find the corresponding change in the configuration file, finally I found an error in the source code, I tried to remove the wrong Spaces in the diagram so that the configuration could be saved correctly
![image](https://user-images.githubusercontent.com/115083919/212674806-c46803d7-ca13-4976-b213-b6c37afc72dc.png)
The error occurs in 'applications/luci-app-frpc/luasrc/model/cbi/frp/config.lua'

**Comment by Beginner-Go** [comment]
8f493e5a8f503aeb0954aea6ca229b76e42cb4f9
