### ISSUE TITLE
luci-theme-design主题样式错误 麻烦更新一下最新源

### ISSUE THREAD

**Issue by threerog** [coolsnowwolf/luci#200]
`luci-theme-design`主题下，服务板块里点击第一个插件服务后左边的菜单栏会全部折叠，再次打开则显示选中了两个菜单
我查了一下`luci-theme-design`作者的仓库好像有更新，麻烦拉取一下

另外`luci-theme-design`作者还提供另一个`luci-app-design-config`主题配置插件，能加入仓库里吗

**Comment by asiaon123** [comment]
同求
