### ISSUE TITLE
更新之后编译easymesh出错，主要应该是batman-adv 2023.3版本引起

### ISSUE THREAD

**Issue by yflwz** [coolsnowwolf/luci#265]
我编译的是K3，在默认的情况下除了加一个easymesh其他什么都不加，没有用多线程，make -J1 V=s直接编译报错。回退到原来batman-adv的2022.3版本可以编译没报错。
./include/linux/kernel.h:955: note: this is the location of the previous definition
  955 | #define clamp_t(type, val, lo, hi) min_t(type, max_t(type, val, lo), hi)
      | 
  CC [M]  /home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.o
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c: In function 'batadv_mcast_mla_rtr_flags_bridge_get':
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c:211:14: error: implicit declaration of function 'br_multicast_has_router_adjacent'; did you mean 'br_multicast_has_querier_adjacent'? [-Werror=implicit-function-declaration]
  211 |         if (!br_multicast_has_router_adjacent(dev, ETH_P_IP))
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              br_multicast_has_querier_adjacent
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c: In function 'batadv_mcast_mla_br_addr_cpy':
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c:538:34: error: 'const struct br_ip' has no member named 'dst'
  538 |                 ip_eth_mc_map(src->dst.ip4, dst);
      |                                  ^~
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c:541:37: error: 'const struct br_ip' has no member named 'dst'
  541 |                 ipv6_eth_mc_map(&src->dst.ip6, dst);
      |                                     ^~
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c: In function 'batadv_mcast_mla_bridge_get':
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c:585:70: error: 'struct br_ip' has no member named 'dst'
  585 |                             ipv4_is_local_multicast(br_ip_entry->addr.dst.ip4))
      |                                                                      ^
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c:589:71: error: 'struct br_ip' has no member named 'dst'
  589 |                             !ipv4_is_local_multicast(br_ip_entry->addr.dst.ip4))
      |                                                                       ^
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c:599:73: error: 'struct br_ip' has no member named 'dst'
  599 |                             ipv6_addr_is_ll_all_nodes(&br_ip_entry->addr.dst.ip6))
      |                                                                         ^
In file included from /home/lwz/lede/staging_dir/target-arm_cortex-a9_musl_eabi/usr/include/mac80211-backport/net/ipv6.h:3,
                 from ./include/net/addrconf.h:63,
                 from /home/lwz/lede/staging_dir/target-arm_cortex-a9_musl_eabi/usr/include/mac80211-backport/net/addrconf.h:4,
                 from /home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c:42:
/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.c:603:66: error: 'struct br_ip' has no member named 'dst'
  603 |                             IPV6_ADDR_MC_SCOPE(&br_ip_entry->addr.dst.ip6) >
      |                                                                  ^
./include/net/ipv6.h:122:11: note: in definition of macro 'IPV6_ADDR_MC_SCOPE'
  122 |         ((a)->s6_addr[1] & 0x0f)        /* nonstandard */
      |           ^
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:262: /home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv/multicast.o] Error 1
make[4]: *** [Makefile:1750: /home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/net/batman-adv] Error 2
make[4]: Leaving directory '/home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.268'
make[3]: *** [Makefile:104: /home/lwz/lede/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/batman-adv-2023.3/.built] Error 2
make[3]: Leaving directory '/home/lwz/lede/feeds/routing/batman-adv'
time: package/feeds/routing/batman-adv/compile#4.08#0.21#4.30
    ERROR: package/feeds/routing/batman-adv failed to build.
make[2]: *** [package/Makefile:116: package/feeds/routing/batman-adv/compile] Error 1
make[2]: Leaving directory '/home/lwz/lede'
make[1]: *** [package/Makefile:110: /home/lwz/lede/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lwz/lede'
make: *** [/home/lwz/lede/include/toplevel.mk:231：world] 错误 2

**Comment by hzjnet** [comment]
换回旧版本就行了：2022.3
