### ISSUE TITLE
进程菜单不显示任何数据

### ISSUE THREAD

**Issue by smallprogram** [coolsnowwolf/luci#279]
![image](https://github.com/coolsnowwolf/luci/assets/6050360/c21920b0-2bfd-4309-a268-a5eba0c4a726)

尝试SSH链接到OP，使用PS命令可以正常显示进程信息

![image](https://github.com/coolsnowwolf/luci/assets/6050360/80185e76-e516-4d6b-9042-45bad468e72d)

请问各位大佬，该如何修复该问题

**Comment by TheLastManT1** [comment]
你的busybox有问题，可能缺少-w参数。如图，左边是正常的，右边是不正常的。
![image](https://github.com/coolsnowwolf/luci/assets/90974162/1e372fca-498a-4795-b27c-dd2d35896b12)
我用apk安装软件包的时候就遇见过，参考博客
https://blog.revincx.icu/posts/never-use-apk-on-openwrt#%E5%B9%95%E5%90%8E%E7%9C%9F%E5%87%B6%E7%9A%84%E6%B5%AE%E7%8E%B0

**Comment by smallprogram** [comment]
> 你的busybox有问题，可能缺少-w参数。如图，左边是正常的，右边是不正常的。 ![image](https://private-user-images.githubusercontent.com/90974162/332762676-1e372fca-498a-4795-b27c-dd2d35896b12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODEyMzgsIm5iZiI6MTcxNjM4MDkzOCwicGF0aCI6Ii85MDk3NDE2Mi8zMzI3NjI2NzYtMWUzNzJmY2EtNDk4YS00Nzk1LWIyN2MtZGQyZDM1ODk2YjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEyMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOTUyOTZkY2JhYWY5YTBiMDBjNGE1MzI5Y2Y5MGVlODY3YmM0NzUyYzU1NTc2MjlkYmI1ZDYyY2E2NzUyZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._B_l2hr9ehJ9Ro_Lfb9FukPVo9-cIZWxkCRhOEsu5eY) 我用apk安装软件包的时候就遇见过，参考博客 https://blog.revincx.icu/posts/never-use-apk-on-openwrt#%E5%B9%95%E5%90%8E%E7%9C%9F%E5%87%B6%E7%9A%84%E6%B5%AE%E7%8E%B0

好的，感谢回复，我试试

**Comment by smallprogram** [comment]
@TheLastManT1 
![image](https://github.com/coolsnowwolf/luci/assets/6050360/896ad7cc-1127-4083-95c5-e0ac3f5fe6d3)
我的-w参数也是没问题的
