### ISSUE TITLE
luci-app-advanced-reboot页面布局混乱

### ISSUE THREAD

**Issue by silenker** [coolsnowwolf/luci#32]
**luci-app-advanced-reboot的luasrc/view/advanced_reboot/advanced_reboot.htm的CSS属性描述的是表格属性（TABLE TR TD），而该htm实际使用的是DIV布局，导致luci 18.06下实际页面布局混乱。把div标签改成css描述的表格属性标签，页面就能正常显示。**
例如：
`<div class="tr cbi-section-table-titles">`
改成：
`<tr class="tr `cbi-section-table-titles">`
Linksys Wrt32x亲测

**Comment by coolsnowwolf** [comment]
请发个 PR 即可
