### ISSUE TITLE
b753998是否改错了

### ISSUE THREAD

**Issue by BoBppy** [coolsnowwolf/luci#34]
https://github.com/coolsnowwolf/luci/commit/b753998006cad2c3751ac801d7164329c5224b8d

cpuinfo在第694行，而修改的在693行
表现为R2S架构仍显示?x4

![TIM图片20200709212028](https://user-images.githubusercontent.com/46050967/87045170-272e9280-c22a-11ea-95c8-68d5fe713596.png)

@dukh1216 提供图片

**Comment by BoBppy** [comment]
还有请问R2S能显示温度吗

**Comment by klever1988** [comment]
cd lede/
wget https://github.com/klever1988/lede/blob/master/enable_autocore.diff
git apply enable_autocore.diff

![image](https://user-images.githubusercontent.com/56048681/89460694-483cc180-d79d-11ea-879e-6ff0bb715f1a.png)

**Comment by dukh1216** [comment]
> cd lede /
> wget https://github.com/klever1988/lede/blob/master/enable_autocore.diff
> git apply enable_autocore.diff
> 
> ![图片](https://user-images.githubusercontent.com/56048681/89460694-483cc180-d79d-11ea-879e-6ff0bb715f1a.png)

git apply enable_autocore.diff一行，提示未能识别的输入，请问是直接在lede目录下输入吗？

**Comment by klever1988** [comment]
> git apply enable_autocore.diff一行，提示未能识别的输入，请问是直接在lede目录下输入吗？
对 不过需要先 ./scripts/feeds install -a

**Comment by dukh1216** [comment]
> > git apply enable_autocore.diff一行，提示未能识别的输入，请问是直接在lede目录下输入吗？
> 
> 对 不过需要先 ./scripts/feeds install -a

还是这样
![7$7NSN}3U$LZQV3EPP8AY{9](https://user-images.githubusercontent.com/56962531/89517318-1e6eb380-d80c-11ea-85e5-4ef297cdba16.png)

**Comment by klever1988** [comment]
> > > git apply enable_autocore.diff一行，提示未能识别的输入，请问是直接在lede目录下输入吗？
> > 
> > 
> > 对 不过需要先 ./scripts/feeds install -a
> 
> 还是这样
> ![7$7NSN}3U$LZQV3EPP8AY{9](https://user-images.githubusercontent.com/56962531/89517318-1e6eb380-d80c-11ea-85e5-4ef297cdba16.png)

抱歉给错diff的地址了，应该是
https://github.com/klever1988/lede/raw/master/enable_autocore.diff

**Comment by dukh1216** [comment]
> > > > git apply enable_autocore.diff一行，提示未能识别的输入，请问是直接在lede目录下输入吗？
> > > 
> > > 
> > > 对 不过需要先 ./scripts/feeds install -a
> > 
> > 
> > 还是这样
> > ![7$7NSN}3U$LZQV3EPP8AY{9](https://user-images.githubusercontent.com/56962531/89517318-1e6eb380-d80c-11ea-85e5-4ef297cdba16.png)
> 
> 抱歉给错diff的地址了，应该是
> https://github.com/klever1988/lede/raw/master/enable_autocore.diff

大佬，重新编译了一次，还是不行(°ー°〃)

**Comment by klever1988** [comment]
> 大佬，重新编译了一次，还是不行(°ー°〃)

Extra packages ->  autocore 要选中编译

**Comment by dukh1216** [comment]
> > 大佬，重新编译了一次，还是不行(°ー°〃)
> 
> Extra packages -> autocore 要选中编译

可以了，感谢大佬耐心指点O(∩_∩)O
