### ISSUE TITLE
luci显示的IPv6地址与实际不符，不论设置如何，显示始终为::1

### ISSUE THREAD

**Issue by IRN-Kawakaze** [coolsnowwolf/luci#58]
问题描述：
https://github.com/coolsnowwolf/lede/issues/6042

找了一下，发现上游openwrt已经修复了该问题：https://github.com/openwrt/luci/commit/461df8b0dc1a9be5fb9e904d8cdc44c6d0cbd6c8

实测修改后可以解决显示与设置不符的问题。

**Comment by AmadeusGhost** [comment]
大佬顺手发个 pr 吧
