### ISSUE TITLE
Contribute to upstream

### ISSUE THREAD

**Issue by aparcar** [coolsnowwolf/luci#69]
Hi, I'm always trying to motivate people to contribute their fork changes to upstream, since I can't find you in the [list of contributors](https://github.com/openwrt/luci/graphs/contributors) I'm wondering if you need some help to get your changes in the main repository?

**Comment by mjyhj** [comment]
This person is addicted to whoring. If you have good resources to introduce him, maybe he will help.
![1](https://user-images.githubusercontent.com/22577418/124798673-36a00300-df86-11eb-802a-d12868fe3e0c.png)

**Comment by aparcar** [comment]
Huh completed?
