### ISSUE TITLE
大佬 luci-app-qbittorrent 能增加 “使用备用 Web UI” 设置功能项吗？

### ISSUE THREAD

**Issue by qingtian110** [coolsnowwolf/luci#94]
想自定义这个设置，但是保存后是不生效的，重启 qbittorrent 后自定义过的设置全部丢失了

希望大佬可以让  luci-app-qbittorrent  支持设置 “使用备用 Web UI” 功能。因为 qbittorrent 默认的webui 不是自适应浏览器的，如果在手机上操作非常困难。如果支持备用Web UI 设置，自己上传UI 到目录就能解决浏览器自适应问题了

![QQ截图20220221190133](https://user-images.githubusercontent.com/87856890/154942608-c546bfa3-5f2b-4874-b925-3c3fe262c1ba.png)

**Comment by WYC-2020** [comment]
我等下看下

**Comment by WYC-2020** [comment]
https://github.com/WYC-2020/luci/commit/464c0ffbefed694795ad17e926e6d17fe1f040d5
@qingtian110

**Comment by qingtian110** [comment]
> 

非常有效！感谢！！！

**Comment by lxl6125** [comment]
分享下你用的 web ui 呗😀

**Comment by qingtian110** [comment]
> 分享下你用的web ui呗😀
我没有专门去搜索哪个ui好用，但是我自己用的这个 https://github.com/WDaan/VueTorrent 

我的需求很简单，只是自适应所有设备的浏览器就够了
